config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"

  resources :accounts, only: [:new, :create]
end

app/models/account.rb
class Account < ActiveRecord::Base
  RESTRICTED_SUBDOMAINS = %w(www)

  belongs_to :owner, class_name: 'User'

  validates :owner, presence: true
  validates :subdomain, presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w\-]+\Z/i, message: "contains invalid characters" },
    exclusion: { in: RESTRICTED_SUBDOMAINS, message: "restricted" }

  accepts_nested_attributes_for :owner

  before_validation :downcase_subdomain

  private

  def downcase_subdomain
    self.subdomain = subdomain.try(:downcase)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to root_path, notice: "Signed up successfully"
    else
      render :new
    end
  end

  private

  def account_params
    params.require(:account).
      permit(:subdomain,
             owner_attributes: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash-#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <h2>Create an Account</h2>

    <%= form_for @account do |form| %>
      <%= form.fields_for :owner do |owner| %>
        <%= form_group_for owner, :name do %>
          <%= owner.text_field :name, class: "form-control" %>
        <% end %>

        <%= form_group_for owner, :email do %>
          <%= owner.email_field :email, class: "form-control" %>
        <% end %>

        <%= form_group_for owner, :password do %>
          <%= owner.password_field :password, class: "form-control" %>
        <% end %>

        <%= form_group_for owner, :password_confirmation do %>
          <%= owner.password_field :password_confirmation, class: "form-control" %>
        <% end %>
      <% end %>

        <%= form_group_for form, :subdomain do %>
          <div class="input-group">
            <p><%= form.text_field :subdomain,
              placeholder: :"Subdomain name",
              class: "form-control" %></p>
            <span class="input-group-addon">.timetracker.dev</span>
          </div>
        <% end %>
        <%= form.submit class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracker</title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header class="container">
      <nav class="navbar navbar-default">
        <div class="navbar-header">
          <%= link_to "Time Tracker", root_path, class: "navbar-brand" %>
        </div>
      </nav>
      <div class="pull-right right-buttons">
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, method: "delete",
            class: "btn btn-default navbar-btn" %>
        <% end %>
      </div>
    </header>

    <div class="container">
      <%= flash_messages if show_layout_flash? %>
      <div class="row">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/welcome/index.html.erb
<div class="col-md-12">
  <div class="jumbotron">
    <h1>Time Tracker</h2>
    <p>Track time with the most awesome time tracking app ever.</p>
    <%= link_to "Create a New Account", new_account_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>